# Generated by Django 4.2.16 on 2024-10-03 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Наименование цвета/окраса')),
            ],
        ),
        migrations.CreateModel(
            name='KittenBreed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название породы')),
                ('description', models.TextField(verbose_name='Описание породы')),
            ],
        ),
        migrations.CreateModel(
            name='Kitten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Кличка котёнка')),
                ('age', models.IntegerField(verbose_name='Возраст, мес.')),
                ('description', models.TextField(verbose_name='Описание')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kittenshow.kittenbreed', verbose_name='Порода')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kittenshow.color', verbose_name='Цвет/окрас')),
                ('user_add', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'age', 'breed', 'user_add')},
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='Оценка')),
                ('kitten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kittenshow.kitten', verbose_name='Котёнок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'unique_together': {('kitten', 'user')},
            },
        ),
    ]
