# Generated by Django 4.2.16 on 2024-10-05 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kittenshow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitten',
            name='rate',
            field=models.FloatField(editable=False, null=True, verbose_name='Средняя оценка'),
        ),
        migrations.AddField(
            model_name='kitten',
            name='rate_count',
            field=models.IntegerField(editable=False, null=True, verbose_name='Оценок'),
        ),
        migrations.AlterField(
            model_name='kitten',
            name='user_add',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.SmallIntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], verbose_name='Оценка'),
        ),
    ]
