# Generated by Django 4.2.16 on 2024-10-05 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kittenshow', '0002_kitten_rate_kitten_rate_count_alter_kitten_user_add_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitten',
            name='user_add',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
